# Generated by Django 5.2.3 on 2025-06-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='合集名称')),
                ('works_count', models.IntegerField(default=0, verbose_name='作品数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '二创合集',
                'verbose_name_plural': '二创合集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='作品标题')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面图片URL')),
                ('view_url', models.URLField(blank=True, null=True, verbose_name='观看链接')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='footprint.collection', verbose_name='所属合集')),
            ],
            options={
                'verbose_name': '作品记录',
                'verbose_name_plural': '作品记录',
                'ordering': ['-id'],
            },
        ),
    ]
