# Generated by Django 5.2.3 on 2025-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
