# Generated by Django 5.2.3 on 2025-06-24 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('singer', models.CharField(blank=True, max_length=200, null=True)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('perform_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewBaseMess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bvid', models.CharField(max_length=100)),
                ('pubtime', models.DateTimeField()),
                ('pic_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SongRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.songs')),
            ],
        ),
        migrations.CreateModel(
            name='ViewRealTimeInformation',
            fields=[
                ('view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='real_time_info', serialize=False, to='main.viewbasemess')),
                ('play', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('fetchtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SongStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.songs')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.style')),
            ],
            options={
                'unique_together': {('song', 'style')},
            },
        ),
    ]
