# Generated by Django 5.2.3 on 2025-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecord',
            name='cover_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
